let activeExam = false, sessionEpoch = 0, mediaEpoch = 0;
const REC={recorder:null,stream:null,pending:false,chunks:[],url:null,clips:[],started:0,recorded:false};
function status(message){document.querySelector('#status').textContent=message;}
function stopRecording(){return new Promise(resolve=>{const r=REC.recorder;if(!r||r.state==='inactive'){REC.stream?.getTracks().forEach(t=>t.stop());return resolve(null)}r.addEventListener('stop',()=>resolve(REC.clips.at(-1)||null),{once:true});r.stop();});}
function cleanupSession(){sessionEpoch++;mediaEpoch++;clearInterval(window.T);window.speechSynthesis?.cancel();stopRecording();REC.pending=false;}
function releaseClips(){if(REC.url)URL.revokeObjectURL(REC.url);REC.url=null;REC.clips.forEach(c=>URL.revokeObjectURL(c.url));REC.clips=[];}
async function startRecording(){
 if(REC.pending||REC.recorder?.state==='recording')return;
 if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder){status('Recording requires a supported browser on HTTPS or localhost. You can still practice aloud.');return}
 REC.pending=true;const epoch=sessionEpoch,media=mediaEpoch;let stream;
 try{stream=await navigator.mediaDevices.getUserMedia({audio:true});if(epoch!==sessionEpoch||media!==mediaEpoch){stream.getTracks().forEach(t=>t.stop());return}
 const r=new MediaRecorder(stream),chunks=[],recordingStarted=Date.now();REC.stream=stream;REC.recorder=r;REC.chunks=chunks;REC.started=Date.now();REC.recorded=false;
 r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
 r.onstop=()=>{const blob=new Blob(chunks,{type:r.mimeType||'audio/webm'});stream.getTracks().forEach(t=>t.stop());if(epoch!==sessionEpoch)return;if(blob.size){const url=URL.createObjectURL(blob);REC.clips.push({url,seconds:Math.max(0,(Date.now()-recordingStarted)/1000)});REC.recorded=true;const a=document.querySelector('#playback');if(a&&!activeExam&&epoch===sessionEpoch){if(REC.url)URL.revokeObjectURL(REC.url);REC.url=URL.createObjectURL(blob);a.src=REC.url;a.hidden=false}}};
 r.start();const b=document.querySelector('#recordBtn');if(b){b.textContent='Stop recording';b.disabled=false}status('Microphone recording is active. Audio stays in this session.');
 }catch(e){stream?.getTracks().forEach(t=>t.stop());status('Microphone unavailable or permission denied. Allow microphone access and try again, or practice aloud.');}finally{if(epoch===sessionEpoch&&media===mediaEpoch)REC.pending=false}
}
async function toggleRecording(){if(REC.recorder?.state==='recording'){await stopRecording();const b=document.querySelector('#recordBtn');if(b){b.textContent=activeExam?'Recording finished':'Record again';b.disabled=activeExam}status('Recording stopped.')}else await startRecording()}
function playSpeech(text,onend=()=>{}){if(!window.speechSynthesis||!window.SpeechSynthesisUtterance){status('Audio playback is unavailable. Use a browser with speech synthesis.');onend(false);return false}window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(text);u.lang='en-US';let ended=false;const end=ok=>{if(!ended){ended=true;onend(ok)}};u.onend=()=>end(true);u.onerror=()=>{status('Audio playback failed. Check your speakers and browser audio settings.');end(false)};speechSynthesis.speak(u);return true}
function countdown(seconds,done,deadline=Date.now()+seconds*1000){clearInterval(window.T);let fired=false;const tick=()=>{const remaining=Math.max(0,Math.ceil((deadline-Date.now())/1000)),e=document.querySelector('#clock');if(e)e.textContent=fmt(remaining);if(!remaining&&!fired){fired=true;clearInterval(window.T);done()}};tick();if(!fired)window.T=setInterval(tick,100);return deadline}
function startTimer(seconds){countdown(seconds,()=>status('Practice time finished.'))}
function requestNavigation(view){if(!activeExam)return nav(view);const dialog=document.createElement('dialog');dialog.innerHTML='<h2>Leave this mock?</h2><p>This attempt will be saved as interrupted. It will not count as a completed mock.</p><button id="keepExam" class="btn" autofocus>Keep practicing</button> <button id="leaveExam">Leave mock</button>';document.body.append(dialog);const trigger=document.activeElement;dialog.onclose=()=>{dialog.remove();trigger?.focus()};dialog.querySelector('#keepExam').onclick=()=>dialog.close();dialog.querySelector('#leaveExam').onclick=()=>{activeExam=false;dialog.close();nav(view)};dialog.showModal()}
async function runFullMock(items=window.buildStandardMock(),standalone=false){
 cleanupSession();releaseClips();activeExam=true;const epoch=sessionEpoch;
 const X={objective:[],open:[],started:Date.now(),interrupted:true},deadlines={};S.inProgress=X;save();let i=0;
 function finishMock(){activeExam=false;X.interrupted=false;X.finished=Date.now();S.attempts++;S.lastMock=X;S.history=[...(Array.isArray(S.history)?S.history:[]),{at:X.finished,objective:X.objective.length,matched:X.objective.filter(a=>a.ok).length,open:X.open.length}].slice(-20);X.objective.filter(a=>!a.ok).forEach(a=>S.mistakes.push({kind:a.type,your:a.y,correct:a.answer,at:X.finished}));S.mistakes=S.mistakes.slice(-500);delete S.inProgress;save();showMockReport(X);const section=document.createElement('div');section.className='card';section.innerHTML='<h2>Speaking playback and self-review</h2>'+rubric('speaking');REC.clips.forEach((c,n)=>{const p=document.createElement('p');p.textContent='Recording '+(n+1)+' · '+Math.round(c.seconds)+' seconds';const a=document.createElement('audio');a.controls=true;a.src=c.url;section.append(p,a)});app.append(section);status('Mock complete. Speaking audio lasts until you reload or start another mock.');}
 function next(){if(epoch!==sessionEpoch||!activeExam)return;if(i>=items.length)return finishMock();const q=items[i];if(q.group&&!deadlines[q.group])deadlines[q.group]=Date.now()+q.groupSeconds*1000;let plays=0,selected=null,submitted=false,startedAt=0,clipStart=REC.clips.length;
 const body=()=>'<span class="eyebrow">'+esc(q.type)+' · '+(i+1)+'/'+items.length+'</span><h2>'+esc(q.prompt||'Listen to the question and answer aloud.')+'</h2>'+(q.image?'<img class="exam-image" src="'+q.image+'" alt="Practice scene; an illustration substitutes for a photograph."><p class="small">Illustration practice: the real DET uses photographs.</p>':'')+(q.display?'<p class="big" id="passage">'+esc(q.display)+'</p>':'')+(q.previous?'<details open><summary>Your initial response</summary><p>'+esc(X.open.find(x=>x.type==='Interactive Writing · Step 1')?.text||'')+'</p></details>':'');
 function renderResponse(){startedAt=Date.now();REC.recorded=false;app.innerHTML='<div class="card">'+body()+(q.audio?'<button class="btn" id="hear">Play audio</button><p class="small">'+(q.plays===Infinity?'Unlimited scenario replay.':q.plays+' total play(s).')+'</p>':'')+(q.fields?q.fields.map((f,n)=>'<label class="field" for="field'+n+'">'+esc(f.label||('Gap '+(n+1)+(f.prefix?' · '+f.prefix+'…':'')))+'</label>'+(f.options?'<select id="field'+n+'"><option value="">Choose a word</option>'+f.options.map(o=>'<option>'+esc(o)+'</option>').join('')+'</select>':'<input id="field'+n+'" autocomplete="off" spellcheck="false">')).join(''):q.kind==='write'?'<label for="openAnswer">Your response</label><textarea id="openAnswer" rows="8" spellcheck="false" autocomplete="off"></textarea>':q.kind==='speak'?'<button class="btn" id="recordBtn">Record answer</button><p class="small">One recording attempt per task. Audio is reviewed after the mock.</p>':q.input?'<label for="examAnswer">'+(q.highlight?'Selected passage words':'Your answer')+'</label><input id="examAnswer" spellcheck="false" autocomplete="off">':'<div class="options">'+q.options.map((o,k)=>'<button data-a="'+k+'" aria-pressed="false">'+esc(o)+'</button>').join('')+'</div>')+'<div id="clock" class="timer">'+fmt(q.seconds)+'</div><button class="btn" id="submitExam">Submit & continue</button></div>';
 const spoken=q.kind==='speak';if(spoken)document.querySelector('#recordBtn').onclick=toggleRecording;
 if(q.audio){const hear=document.querySelector('#hear');if(spoken)document.querySelector('#recordBtn').disabled=true;hear.onclick=()=>{if(plays>=q.plays)return;plays++;hear.disabled=true;playSpeech(q.audio,()=>{if(epoch!==sessionEpoch||submitted)return;hear.disabled=plays>=q.plays;if(spoken){document.querySelector('#recordBtn').disabled=false;countdown(q.seconds,()=>finish(true));startRecording()}});hear.textContent='Play audio ('+plays+(q.plays===Infinity?'':'/'+q.plays)+')';};if(q.plays!==Infinity)hear.click()}
 document.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>{selected=+b.dataset.a;document.querySelectorAll('[data-a]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));if(q.type==='Read and Select')finish()});
 if(q.highlight){document.querySelector('#passage').onpointerup=()=>{const s=window.getSelection();if(s&&document.querySelector('#passage').contains(s.anchorNode)&&document.querySelector('#passage').contains(s.focusNode))document.querySelector('#examAnswer').value=s.toString()};}
 document.querySelector('#submitExam').onclick=()=>finish(false);
 document.querySelectorAll('input,textarea').forEach(el=>el.oninput=()=>{S.draft={type:q.type,text:el.value};save()});
 if(!(spoken&&q.audio))countdown(q.seconds,()=>finish(true),q.group?deadlines[q.group]:undefined);document.querySelector('input,textarea,select,#recordBtn,[data-a]')?.focus();}
 async function finish(timedOut=false){if(submitted||epoch!==sessionEpoch||!activeExam)return;
 if(q.fields?.some((f,n)=>!document.querySelector('#field'+n).value)&&!timedOut&&q.type.includes('Complete the Sentences')){status('Choose a word for every gap before continuing.');return}
 submitted=true;mediaEpoch++;REC.pending=false;clearInterval(window.T);window.speechSynthesis?.cancel();const text=q.kind==='write'?document.querySelector('#openAnswer').value:q.input?document.querySelector('#examAnswer').value:null;
 if(q.kind==='speak')await stopRecording();if(epoch!==sessionEpoch||!activeExam)return;
 if(q.kind){X.open.push({type:q.type,skill:q.skill,text:q.kind==='write'?text:'',words:q.kind==='write'?words(text):null,recorded:q.kind==='speak'?REC.clips.length>clipStart:null,duration:Math.max(0,(Date.now()-startedAt)/1000)});}else{
 const answers=q.fields?q.fields.map((f,n)=>document.querySelector('#field'+n).value):[q.input?text:selected],targets=q.fields?q.fields.map(f=>f.answer):[q.answer];answers.forEach((y,n)=>X.objective.push({type:q.type,skill:q.skill,y,answer:q.fields?targets[n]:q.options?q.options[q.answer]:q.answer,ok:q.fields||q.input?norm(y)===norm(targets[n]):y===targets[n]}));}
 if(q.feedback&&!timedOut){app.innerHTML='<div class="card good"><h2>Conversation reply</h2><p>'+esc(q.options[q.answer])+'</p><button class="btn" id="follow">Continue conversation</button></div>';document.querySelector('#follow').onclick=advance;countdown(Math.max(0,(deadlines[q.group]-Date.now())/1000),advance,deadlines[q.group]);}else advance();}
 let advanced=false;function advance(){if(advanced||epoch!==sessionEpoch||!activeExam)return;advanced=true;clearInterval(window.T);i++;delete S.draft;save();next()}
 if(q.prep){app.innerHTML='<div class="card">'+body()+'<p>Prepare mentally. Your response time starts after this preparation period.</p><div id="clock" class="timer">'+fmt(q.prep)+'</div><button class="btn" id="beginResponse">Begin response</button></div>';let prepared=false;const begin=()=>{if(prepared||epoch!==sessionEpoch)return;prepared=true;clearInterval(window.T);renderResponse();if(q.kind==='speak')startRecording()};document.querySelector('#beginResponse').onclick=begin;countdown(q.prep,begin);}else renderResponse();
 }
 next();
}
function runInteractive(){runFullMock(window.buildStandardMock().filter(q=>q.type==='Interactive Speaking'),true)}
window.addEventListener('pagehide',()=>{cleanupSession();releaseClips()});
